# - name: Run etcd
#   shell: systemctl enable etcd && systemctl start etcd
#   delegate_to: "{{item}}"
#   #loop: "{{groups['k8s-master']}}"  #
#   with_items: "{{groups['k8s-master']}}"


# - name: cp copy shell
#   copy:
#     src: "{{ keys.gen_etcd }}"
#     dest: /opt/kubernetes/
#     mode: '0644'
#   delegate_to: "{{item}}"
#   with_items: "{{groups['k8s-master']}}"
# - name: cp run shell
#   shell: cd /opt/kubernetes && bash ./gen-etcd.sh  &&  cp -r ./etcd/etcd.service  /usr/lib/systemd/system/etcd.service  &&  systemctl daemon-reload
#   delegate_to: "{{item}}"
#   with_items: "{{groups['k8s-master']}}"


- name: etcd copy shell
  copy:
    src: "{{ keys.etcd }}"
    dest: /opt/kubernetes/
    mode: '0755'
  run_once: true  #执行一次
  delegate_to: "192.168.56.101"
- name: etcd run shell
  shell:  /opt/kubernetes/etcd-cluster.sh get | xargs -I var echo var  #{Network:121.21.0.0/16,Backend:{Type:vxlan}}
  #  bash  /opt/kubernetes/etcd-cluster.sh s | awk 'NR==5{print$6}' | xargs -I var echo var  #3.2.26
  # bash  /opt/kubernetes/etcd-cluster.sh s | awk 'NR==5{print$6}' | xargs -I var [ var  !=  "3.2.26" ] || { echo "status success"; }
  delegate_to: "192.168.56.101"
  register: etcd_val
  #when: ansible_default_ipv4.address == "192.168.56.101"
