# - name: copy node
#   copy:
#     src: "{{item}}"
#     dest: /opt/kubernetes/
#     mode: '0744'
#   with_fileglob: 
#     -  "{{ keys.cluster }}"

# kubectl certificate approve node-csr...
# - name:
#   file: path=/opt/kubernetes/config/kubelet.kubeconfig state=absent


- name: run kubelet
  shell: cd /opt/kubernetes && rm -rf ./kubelet && bash ./gen-kubelet.sh    && cp -r ./kubelet/kubelet.service /usr/lib/systemd/system  && systemctl daemon-reload

- name: service kubelet start
  service:
     name=kubelet  state=started  enabled=yes


# - name:  run kube-proxy
#   shell: cd /opt/kubernetes && rm -rf ./kube-proxy && bash ./gen-kube-proxy.sh && cp -r ./kube-proxy/kube-proxy.service /usr/lib/systemd/system  && systemctl daemon-reload


# - name: service kube-proxy start
#   service:
#      name=kube-proxy  state=started  enabled=yes